services:
  jarvis-api:
    build:
      context: .
      dockerfile: .docker/Dockerfile-api
    container_name: jarvis-api
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8200:8200"
    depends_on:
      - jarvis-ollama
    environment:
      - OLLAMA_HOST=jarvis-ollama
      - OLLAMA_PORT=11434

  jarvis-ollama:
    build:
      context: .
      dockerfile: .docker/Dockerfile-ollama
    container_name: jarvis-ollama
    ports:
      - "11434:11434"
    volumes:
      - .:/app
    working_dir: /app

networks:
    default:
      driver: bridge
