FROM python:3.11-slim

# Dépendances système pour l'audio et Whisper
RUN apt-get update && apt-get install -y \
    portaudio19-dev \
    ffmpeg \
    libasound2-dev \
    && rm -rf /var/lib/apt/lists/*

# Ajout de webrtcvad pour la détection de voix
RUN pip install webrtcvad

WORKDIR /app

COPY ../voice/ /app/

# Dépendances Python
RUN pip install --upgrade pip && \
    pip install pyaudio numpy openai-whisper requests SpeechRecognition

CMD ["python", "jarvis.py"]
