FROM python:3.11-slim

# Installe prérequis système
RUN apt-get update && apt-get install -y \
    git \
    curl \
    ffmpeg \
    build-essential \
    portaudio19-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY .docker/requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY ../api/ api/
COPY ../voice/ voice/

EXPOSE 8200

CMD ["uvicorn", "api.llm_api:app", "--host", "0.0.0.0", "--port", "8200"]

